services:
  - type: web
    name: api-scoring-projet7
    env: python
    plan: free
    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=8000
    autoDeploy: true

  - type: web
    name: streamlit-app
    env: python
    plan: free
    buildCommand: pip install -r streamlit_app/requirements.txt
    startCommand: streamlit run streamlit_app/app.py --server.port=10000 --server.address 0.0.0.0
    autoDeploy: true