name: Deploy FastAPI+Streamlit to Render

on:
  push:
    branches:
      - main

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repository
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install API dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Lancer les tests unitaires
        run: |
          pytest || echo "Exécution des tests unitaires"

      - name: Déployer via Render Deploy Hook
        run: curl "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
   
   deploy-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repository
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install API dependencies
        run: |
          cd streamlit_app
          pip install -r requirements.txt

      - name: Déployer via Render Deploy Hook
        run: curl "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}   