name: Deploy FastAPI and Streamlit to Render

on:
  push:
    branches:
      - main

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repository
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Installer les dépendances API
        run: |
          cd app
          pip install -r requirements.txt

      - name: Lancer les tests unitaires
        run: |
          pytest || echo "Exécution des tests unitaires"

      - name: Déployer via Render Deploy Hook
        run: curl "$RENDER_DEPLOY_HOOK_API"
        env:
          RENDER_DEPLOY_HOOK_API: ${{ secrets.RENDER_DEPLOY_HOOK_API }}

  deploy-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repository
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Installer les dépendances Streamlit
        run: |
          cd streamlit_app
          pip install -r requirements.txt

      - name: Déployer via Render Deploy Hook
        run: curl "$RENDER_DEPLOY_HOOK_STREAMLIT"
        env:
          RENDER_DEPLOY_HOOK_STREAMLIT: ${{ secrets.RENDER_DEPLOY_HOOK_STREAMLIT }}